//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INotifier")]
    public interface INotifier {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifier/Notify", ReplyAction="http://tempuri.org/INotifier/NotifyResponse")]
        void Notify();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifier/Notify", ReplyAction="http://tempuri.org/INotifier/NotifyResponse")]
        System.Threading.Tasks.Task NotifyAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotifierChannel : Client.ServiceReference1.INotifier, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotifierClient : System.ServiceModel.ClientBase<Client.ServiceReference1.INotifier>, Client.ServiceReference1.INotifier {
        
        public NotifierClient() {
        }
        
        public NotifierClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotifierClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotifierClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotifierClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Notify() {
            base.Channel.Notify();
        }
        
        public System.Threading.Tasks.Task NotifyAsync() {
            return base.Channel.NotifyAsync();
        }
    }
}
