//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IATMMonitor")]
    public interface IATMMonitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMMonitor/GetReport", ReplyAction="http://tempuri.org/IATMMonitor/GetReportResponse")]
        string GetReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMMonitor/GetReport", ReplyAction="http://tempuri.org/IATMMonitor/GetReportResponse")]
        System.Threading.Tasks.Task<string> GetReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IATMMonitorChannel : Client.ServiceReference1.IATMMonitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATMMonitorClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IATMMonitor>, Client.ServiceReference1.IATMMonitor {
        
        public ATMMonitorClient() {
        }
        
        public ATMMonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATMMonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMMonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMMonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetReport() {
            return base.Channel.GetReport();
        }
        
        public System.Threading.Tasks.Task<string> GetReportAsync() {
            return base.Channel.GetReportAsync();
        }
    }
}
